{% set name = "asio" %}
{% set version = "1.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chriskohlhoff/{{ name }}/archive/{{ name }}-{{ version.replace('.','-') }}.tar.gz
  sha256: 5b12ce2cdb658025e67785f954f74b052709cfc9b5941b8fb889c049b0955e1d

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/include/asio.hpp  # [unix]
    - test -f $PREFIX/include/asio/error.hpp  # [unix]
    - if exist %PREFIX%\\Library\\include\\asio.hpp (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\include\\asio\\error.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/chriskohlhoff/asio
  license: BSL-1.0
  license_file: asio/COPYING
  summary: |
    Asio is a cross-platform C++ library for network and low-level I/O programming that
    provides developers with a consistent asynchronous model using a modern C++ approach.

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
