{% set name = "asio" %}
{% set version = "1.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chriskohlhoff/{{ name }}/archive/{{ name }}-{{ version.replace('.','-') }}.tar.gz
  sha256: cbcaaba0f66722787b1a7c33afe1befb3a012b5af3ad7da7ff0f6b8c9b7a8a5b

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - autoconf  # [unix]
    - automake  # [unix]
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/include/asio.hpp  # [unix]
    - test -f $PREFIX/include/asio/error.hpp  # [unix]
    - if exist %PREFIX%\\Library\\include\\asio.hpp (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\include\\asio\\error.hpp (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/chriskohlhoff/asio
  license: BSL-1.0
  license_file: asio/COPYING
  summary: |
    Asio is a cross-platform C++ library for network and low-level I/O programming that
    provides developers with a consistent asynchronous model using a modern C++ approach.

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
